---
roles:
  - name: geerlingguy.security
  - name: geerlingguy.docker
  - name: gantsign.oh-my-zsh
  - name: geerlingguy.firewall
  - name: geerlingguy.nfs

collections:
  - name: community.docker
  - name: community.general
  - name: ansible.posix
