---
roles:
  - name: geerlingguy.security
  - name: geerlingguy.docker
  - name: viasite-ansible.zsh
  - name: geerlingguy.firewall
  - name: geerlingguy.nfs

collections:
  - name: community.docker
  - name: ansible.posix
