---
- name: Remove GitHub HTTPS to SSH rewrite from login user
  community.general.git_config:
    name: url.ssh://git@github.com/.insteadOf
    scope: global
    state: absent
  become: true
  become_user: "{{ ansible_user }}"

- name: Remove GitHub HTTPS to SSH rewrite from root
  community.general.git_config:
    name: url.ssh://git@github.com/.insteadOf
    scope: global
    state: absent
  become: true
